---
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: Step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          echo 'delta' > delta.html
          cd ..
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: assets-for-download
          path: downloads
      - name: Step 4 upload assets
        uses: alexellis/upload-assets@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["downloads"]'