---
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main]
jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: Step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'charlie' > charlie.html
          echo 'delta' > delta.html
          echo 'echo' > echo.html
          cd ..
      - uses: benjlevesque/short-sha@v2.1
        id: short-sha
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        with:
          name: ${{ env.SHA }}
          tag: ${{ env.SHA }}
          makeLatest: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: downloads/*
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true
